// This file is generated by npm run build:icons

export type AllIconTypes =
	| "icons/adventures-quests"
	| "icons/all-quests"
	| "icons/clock"
	| "icons/close"
	| "icons/detective-quests"
	| "icons/horror-quests"
	| "icons/icon/person"
	| "icons/logo"
	| "icons/mistic-quests"
	| "icons/person"
	| "icons/puzzle"
	| "icons/sciFi-quests"
	| "icons/social"
	| "icons/twitter"
	| "icons/youtube";
