export * from "./Icon/Icon";
export * from "./Logo/Logo";
export * from "./Header/Header";
export * from "./AllGames/AllGames";
export * from "./Socials/Socials";
export * from "./CustomButton/CustomButton";
export * from "./Loader/Loader";
export * from "./Input/Input";
export * from './OrderForm/OrderForm'
export * from './SignUpForm/SignUpForm'
